dist: trusty
language: r
sudo: false

env:
  matrix:
  - NOT_CRAN=true

cache:
  - packages

install:
  - wget https://saucelabs.com/downloads/sc-4.4.5-linux.tar.gz
  - tar zxf sc-4.4.5-linux.tar.gz
  - sc-4.4.5-linux/bin/sc -u $SAUCE_USERNAME -k $SAUCE_ACCESS_KEY --no-ssl-bump-domains "localhost" &
  - export pid=$!
  - Rscript -e "install.packages(c('shiny', 'RSelenium', 'testthat', 'devtools', 'MCMCpack', 'shinyjs', 'ggplot2'))"
  - Rscript -e "install.packages(c('graphics', 'grid', 'gridExtra', 'plotly', 'plyr', 'reshape2', 'stats', 'future'))"

before_script:
  - R -e "shiny::runApp(port=3000)" &
  - sleep 10
  - curl "http://localhost:3000"

script:
  - Rscript -e "testthat::test_dir('tests', reporter='stop')"

after_script:
  - kill $pid
  - sleep 30

notifications:
  email: false
