dist: trusty
language: r
sudo: false

env:
  matrix:
  - NOT_CRAN=true

cache:
  - packages
  
install:
  - Rscript -e "install.packages('devtools')"
  - Rscript -e "devtools::install_github('annecori/EpiEstim', ref = 'hackout3')"
  - Rscript -e "devtools::install_github('nickreich/coarseDataTools', ref = 'hackout3')"

before_script:
  - R -e "shiny::runApp(port=3000)" > out.txt 2>&1 &
  - sleep 10

script:
  - R -e "out<-testthat::test_dir('tests', reporter=c('summary', 'list', 'fail')); out"
  
after_script:
  - cat out.txt

addons:
  sauce_connect:
    no_ssl_bump_domains: localhost

notifications:
  email: false
