dist: trusty
language: r
sudo: false

env:
  matrix:
  - NOT_CRAN=true

cache:
  - packages

install:
  - Rscript -e "install.packages(c('shiny', 'RSelenium', 'testthat', 'devtools', 'MCMCpack', 'shinyjs', 'ggplot2'))"
  - Rscript -e "install.packages(c('graphics', 'grid', 'gridExtra', 'plotly', 'plyr', 'reshape2', 'stats', 'future'))"

before_script:
  - R -e "shiny::runApp(port=3000)" &
  - sleep 10

script:
  - Rscript -e "testthat::test_dir('tests', reporter='stop')"

addons:
  sauce_connect: true

notifications:
  email: false
