dist: trusty
language: r
sudo: false

env:
  matrix:
  - NOT_CRAN=true

cache:
  - packages
  
install:
  - Rscript -e "if (!require('pacman')) install.packages('pacman')"
  - Rscript -e "pacman::p_load('shiny', 'RSelenium', 'testthat', 'devtools', 'MCMCpack', 'shinyjs', 'ggplot2')"
  - Rscript -e "pacman::p_load('graphics', 'grid', 'gridExtra', 'plotly', 'plyr', 'reshape2', 'stats', 'future')"
  - Rscript -e "devtools::install_github('nickreich/coarseDataTools', ref = 'hackout3')"

before_script:
  - R -e "shiny::runApp(port=3000)" > out.txt 2>&1 &
  - sleep 10

script:
  - R -e "out<-testthat::test_dir('tests', reporter=c('summary', 'list', 'fail')); out"
  
after_script:
  - cat out.txt

addons:
  sauce_connect:
    no_ssl_bump_domains: localhost

notifications:
  email: false
