dist: trusty
language: r
sudo: false

env:
  matrix:
  - NOT_CRAN=true

cache:
  - packages

install:
  - Rscript -e "install.packages(c('shiny', 'RSelenium', 'testthat'))"

before_script:
  - R -e "shiny::runApp(port=6000)" &
script:
  - Rscript -e "testthat::test_dir('tests')"

addons:
  sauce_connect:
    no_ssl_bump_domains: localhost

notifications:
  email: false
