language: r
env:
  global:
  - NOT_CRAN=true
  - browser=chrome platform="Windows 10"
  matrix:
  - suite=001
  - suite=002
  - suite=003
  - suite=004.01
  - suite=004.02
  - suite=004.03.1
  - suite=004.03.2
  - suite=004.03.3
  - suite=004.04
  - suite=004.05
  - suite=004.06
  - suite=004.07
  - suite=004.08
cache:
- packages
r:
- release
r_github_packages:
  - johndharrison/binman
  - johndharrison/wdman
before_script:
  - |
    cd tests/testthat
    # Remove all test files not in current test suite
    ls
    ls | grep -P "^testSuite(?!$suite)" | xargs -d"\n" rm
    ls
    cd ../../
script:
  - |
    travis_retry R CMD build .
    travis_retry travis_wait 60 R CMD check EpiEstimApp*tar.gz
after_failure:
  - find *Rcheck -name '*.fail' -print -exec cat '{}' \;
  - find *Rcheck -name '*.log' -print -exec cat '{}' \;
addons:
  sauce_connect:
    no_ssl_bump_domains: localhost
notifications:
  email: false
  slack:
    secure: gJWBgTlMkV1DsCgTaE2TLBfop/Zg/rSKhvUsNOrv67CsvR0V1oRdhBoXsBIgSL/z5LN8PF1WzRat9Q6YVOF8ePj1w6iluzhxbMOquzFZq/7glh/UGE07VPM4nBhWPP78mB4pAiY2PO85mySGqu5/OZRHrJxzyuTTt1vmdN8XRqkFVDx6/GwiqBZSrQZ/riZY2z5RGlZfhiGUcyszlDiRFSAineFEHH8pbTBs4uFjP63SiuHJPUIzoKe+edD7qmBJawU3Yq5ExC0Jt2cleSoABd5ATrT6SGSWePxJZ9/LeF9hLeCqxE/PjGLRMM6G/I8vnGg9I67RzP1Wl9oZ0WoFjS1yPP9PnsO8uxdPyj60OCWZmXj1uJopYVRPjZLdTXdoJnC7honIkn0g7IoE7vm5soeRUN1mgPRycF1BLqpZUN25BnOx9DOBSQBhzKP6Ob0+Eu0GBH4l7y28YNsXkWymQFDQOWOycUTO9KxeInvQQpb6lqKh86kjAJlwZmsbGKrU6gmfMDiaslp3gKU4P7HEr5eR6p5KVQKW428uEBEM+J6khXAj9lNLIQgX8eLiFARbpM/XFmc4/Go7J/D/Z4tcRHvxmWdGaEhKqeJoq9x7439VyvrZ8Tx3hUGksgTUKx7el0VcQGZ5fjyYO7PKWPAO8g9ldbYhBQ5lok9WYbpx3mI=
