dist: trusty
language: r
sudo: false

env:
  matrix:
  - NOT_CRAN=true

cache:
  - packages

r_github_packages:
  - johndharrison/semver

r_packages:
  - shiny
  - RSelenium
  - testthat

install:
  - echo "There is nothing to do here, but travis errors if we don't have an install block"

before_script:
  - R -e "shiny::runApp(port=6000)" &
script:
  - Rscript -e "testthat::test_dir('tests')"

addons:
  sauce_connect:
    no_ssl_bump_domains: localhost

notifications:
  email: false
