dist: trusty
language: r
sudo: false

env:
  matrix:
  - NOT_CRAN=true

cache:
  - packages

install:
  - echo "There is nothing to do here, but we need the install bit for anything to run"

before_script:
  - R -e "shiny::runApp(port=3000)" &
  - sleep 10

script:
  - R -e "testthat::test_dir('tests', reporter=c('summary', 'fail'))"

addons:
  sauce_connect: true

notifications:
  email: false

r_packages:
  - shiny
  - RSelenium
  - testthat
  - devtools
  - MCMCpack
  - shinyjs
  - ggplot2
  - graphics
  - grid
  - gridExtra
  - plotly
  - plyr
  - reshape2
  - stats
  - future
  
r_github_packages:
  - nickreich/coarseDataTools
  - acori/EpiEstim